### PR TITLE
PR: add AZH signal samples (2nd try)

### PR DESCRIPTION
**Pull request by LukasEbeling**
azh_htt_zll samples added (hopefully) with correct format and naming

### CODE REVIEW

**Review by riga — APPROVED** [review]
Looking good!

**Review by riga — CHANGES_REQUESTED** [review]
Really nice!

Just one thing: can you add the main generator at the end of each dataset name (`..._amcatnlo` in you case)? That's also why the CI tests with the latest addition of the changes in `master`.

**Comment by LukasEbeling** [comment]
Hey Marcel, I just added the generator to the dataset name and also to the ash processes -> was that correct?

**Comment by riga** [comment]
@LukasEbeling For the datasets it's correct yes :+1:
However, could you remove them again from the processes? They should - in principle - be defined independent of the generator.

**Review by riga — APPROVED** [review]
Yup, looking good.

**Pull request merged**
