### PR TITLE
Update st s-channel cross sections.

### PR DESCRIPTION
**Pull request by riga**
This small PR updates our s-channel single-top cross sections.

We used NLO values so far but there was actually an update last month in
https://twiki.cern.ch/twiki/bin/view/LHCPhysics/SingleTopNNLORef?rev=21#Single_top_quark_s_channel_cross
which provided updates to the t/tbar specific cross sections at **NN**LO, even for 13.6 TeV.

I updated the nominal values as well as scale uncertainties.

### CODE REVIEW

**Review by nprouvost — CHANGES_REQUESTED** [review]
Remove comments, since they are already explained at the top of the file, else LGTM

**Review by nprouvost — APPROVED** [review]
lgtm

**Comment by riga** [comment]
@mafrahm @dsavoiu I checked your configs and saw that you're both using single-top processes processes, so I you guys should sign off as well before we can merge.

**Review by dsavoiu — APPROVED** [review]
Hi @riga, thanks for the PR and the ping! It's great to update this XS to NNLO. Looks like the uncertainty breakdown for the new XS is not as detailed, but after checking with @jomatthi I don't think we are relying on those numbers at the moment in the analysis, so it's fine for us to merge this.

**Comment by riga** [comment]
Ok great, thanks for the additional check :+1:

**Pull request merged**
